name: Discord Notifications

on:
  push:
    branches:
      - main  # Send notifications only when pushing to main

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Notification
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"🚀 New commit pushed to main! \n\n**Commit:** ${{ github.event.head_commit.message }} \n**By:** ${{ github.event.head_commit.author.name }} \n[View Commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})\"}" \
               "${{ secrets.DISCORD_WEBHOOK_URL }}"
